version: '3'
services:
#  redis:
#    expose:
#      - 6379
#    ports:
#      - "63793:6379"
#    image: "redis:alpine"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres-data-2:/var/lib/postgresql/data
    ports:
      - 5442:5432
    container_name: dbIntricom
#  my-mongoDB:
#    image: mongo:latest
#    ports:
#      - 27018:27017
#    volumes:
#      - db-data:/data/db
#      - mongo-config:/data/configdb
volumes:
  db-data:
#  mongo-config:
  postgres-data-2:
      #  nginx:
#    image: nginx
#    ports:
#      - 8000:80
#    volumes:
#      - ./html:/usr/share/nginx/html
      #- ./nginx/nginx.conf:/etc/nginx/nginx.conf
